name: xpensure
description: Company Expense Management App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  image_picker: ^1.1.1
  file_picker: ^8.2.3
  path: ^1.9.0
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.12
  fl_chart: ^1.0.0
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.1
  path_provider: ^2.0.15
  syncfusion_flutter_charts: ^23.1.44
  csv: ^5.0.0
  permission_handler: ^11.0.1
  share_plus: ^7.2.2
   # Add these for better network image handling
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.1
  open_file: ^3.3.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png

# YEH LAST MEIN ADD KARO â–¼
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#00000000"  # Transparent background
  adaptive_icon_foreground: "assets/logo/androidicon.png"
